name: Deploy static content to Pages
on:
  push:
    branches: ["main"]
    paths: 
    - "./Builds/**"
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          # Upload Builds repository
          path: "./Builds"
      - id: deployment
        uses: actions/deploy-pages@v1
      # Upload to Itch
      - uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html5
          ITCH_GAME: whisker-president-3c
          ITCH_USER: scrubers
          PACKAGE: ./Builds